### ISSUE TITLE
outdated

### ISSUE THREAD

**Issue by z0z0r4** [nwesterhausen/py-mcdata-to-json#1]
The new version of minecraft seems to be dead
Not found "Level" in nbt!

**Comment by nwesterhausen** [comment]
I tested with existing code and was crashing at leveldat processing step. I modified the code and was no longer crashing. Released 0.4.0.0 so please try that and let me know if its working for you.

**Comment by z0z0r4** [comment]
I think is .mca param error, see wiki.vg
mca_reader.py

**Comment by z0z0r4** [comment]
1.17 or 1.18 updated

**Comment by nwesterhausen** [comment]
I'll take another look at it then. I only tested the change with a new (empty) world with 1.19 server, since I didn't have anything else to test it on that was with the current version.

**Comment by z0z0r4** [comment]
these, replaced level in chunk information
![image](https://user-images.githubusercontent.com/78744121/187010042-9ba38c52-08f8-406c-b804-cb97cefce702.png)

**Comment by z0z0r4** [comment]
![image](https://user-images.githubusercontent.com/78744121/187010166-0f5ea9e3-2443-49f6-ba5f-68305bbb2767.png)
https://minecraft.fandom.com/wiki/Chunk_format
no longer use level
